# Generated by Django 4.2.1 on 2023-06-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlgeoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginRegisterLogout',
        ),
    ]
