# Generated by Django 3.2.12 on 2023-05-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Particles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIMESTEP', models.IntegerField()),
                ('TYPE', models.IntegerField()),
                ('X', models.FloatField()),
                ('Z', models.FloatField()),
                ('V_ACC', models.FloatField()),
                ('RADIUS', models.FloatField()),
            ],
        ),
    ]
